//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.Sigepro.FrontEnd.AppLogic.WsNodoPagamenti {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsNodoPagamenti.IWsNodoPagamentiService")]
    public interface IWsNodoPagamentiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsNodoPagamentiService/GetConfigurazione", ReplyAction="http://tempuri.org/IWsNodoPagamentiService/GetConfigurazioneResponse")]
        Init.SIGePro.Manager.DTO.Pagamenti.ConfigurazionePagamentiNodoPagamenti GetConfigurazione(string token, string software, string codiceComune);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsNodoPagamentiServiceChannel : Init.Sigepro.FrontEnd.AppLogic.WsNodoPagamenti.IWsNodoPagamentiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsNodoPagamentiServiceClient : System.ServiceModel.ClientBase<Init.Sigepro.FrontEnd.AppLogic.WsNodoPagamenti.IWsNodoPagamentiService>, Init.Sigepro.FrontEnd.AppLogic.WsNodoPagamenti.IWsNodoPagamentiService {
        
        public WsNodoPagamentiServiceClient() {
        }
        
        public WsNodoPagamentiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsNodoPagamentiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsNodoPagamentiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsNodoPagamentiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Init.SIGePro.Manager.DTO.Pagamenti.ConfigurazionePagamentiNodoPagamenti GetConfigurazione(string token, string software, string codiceComune) {
            return base.Channel.GetConfigurazione(token, software, codiceComune);
        }
    }
}
