//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigepro.net.Antenne {
    
    
    public partial class elemento_lista_antenne {
        
        /// <summary>
        /// ltrNumeroPratica control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrNumeroPratica;
        
        /// <summary>
        /// ltrNumeroProtocollo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrNumeroProtocollo;
        
        /// <summary>
        /// txtRichiedente control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtRichiedente;
        
        /// <summary>
        /// txtIntervento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtIntervento;
        
        /// <summary>
        /// allegatiIntervento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sigepro.net.Antenne.allegati_pratica_antenne allegatiIntervento;
        
        /// <summary>
        /// allegatiEndoprocedimento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sigepro.net.Antenne.allegati_pratica_antenne allegatiEndoprocedimento;
        
        /// <summary>
        /// allegatiMovimenti control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Sigepro.net.Antenne.allegati_pratica_antenne allegatiMovimenti;
    }
}
