//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IstanzeDyn2Dati", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Data")]
    [System.SerializableAttribute()]
    public partial class IstanzeDyn2Dati : Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.BaseDataClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2Campi CampoDinamicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodiceistanzaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FkD2cIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdcomuneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IndiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IndiceMolteplicitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValoredecodificatoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2Campi CampoDinamico {
            get {
                return this.CampoDinamicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CampoDinamicoField, value) != true)) {
                    this.CampoDinamicoField = value;
                    this.RaisePropertyChanged("CampoDinamico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Codiceistanza {
            get {
                return this.CodiceistanzaField;
            }
            set {
                if ((this.CodiceistanzaField.Equals(value) != true)) {
                    this.CodiceistanzaField = value;
                    this.RaisePropertyChanged("Codiceistanza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FkD2cId {
            get {
                return this.FkD2cIdField;
            }
            set {
                if ((this.FkD2cIdField.Equals(value) != true)) {
                    this.FkD2cIdField = value;
                    this.RaisePropertyChanged("FkD2cId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idcomune {
            get {
                return this.IdcomuneField;
            }
            set {
                if ((object.ReferenceEquals(this.IdcomuneField, value) != true)) {
                    this.IdcomuneField = value;
                    this.RaisePropertyChanged("Idcomune");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Indice {
            get {
                return this.IndiceField;
            }
            set {
                if ((this.IndiceField.Equals(value) != true)) {
                    this.IndiceField = value;
                    this.RaisePropertyChanged("Indice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IndiceMolteplicita {
            get {
                return this.IndiceMolteplicitaField;
            }
            set {
                if ((this.IndiceMolteplicitaField.Equals(value) != true)) {
                    this.IndiceMolteplicitaField = value;
                    this.RaisePropertyChanged("IndiceMolteplicita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valore {
            get {
                return this.ValoreField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoreField, value) != true)) {
                    this.ValoreField = value;
                    this.RaisePropertyChanged("Valore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valoredecodificato {
            get {
                return this.ValoredecodificatoField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoredecodificatoField, value) != true)) {
                    this.ValoredecodificatoField = value;
                    this.RaisePropertyChanged("Valoredecodificato");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataClass", Namespace="http://schemas.datacontract.org/2004/07/PersonalLib2.Sql")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.BaseDataClass))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2Campi))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2ModelliT))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2CampiProprieta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2CampiScript))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2ModelliScript))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2ModelliD))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.IstanzeDyn2Dati))]
    public partial class DataClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _dataTableNameField;
        
        private string OrderByk__BackingFieldField;
        
        private string[] OthersJoinClausek__BackingFieldField;
        
        private string[] OthersSelectColumnsk__BackingFieldField;
        
        private string[] OthersTablesk__BackingFieldField;
        
        private string[] OthersWhereClausek__BackingFieldField;
        
        private string SelectColumnsk__BackingFieldField;
        
        private Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.useForeignEnum UseForeignk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _dataTableName {
            get {
                return this._dataTableNameField;
            }
            set {
                if ((object.ReferenceEquals(this._dataTableNameField, value) != true)) {
                    this._dataTableNameField = value;
                    this.RaisePropertyChanged("_dataTableName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OrderBy>k__BackingField", IsRequired=true)]
        public string OrderByk__BackingField {
            get {
                return this.OrderByk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderByk__BackingFieldField, value) != true)) {
                    this.OrderByk__BackingFieldField = value;
                    this.RaisePropertyChanged("OrderByk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OthersJoinClause>k__BackingField", IsRequired=true)]
        public string[] OthersJoinClausek__BackingField {
            get {
                return this.OthersJoinClausek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.OthersJoinClausek__BackingFieldField, value) != true)) {
                    this.OthersJoinClausek__BackingFieldField = value;
                    this.RaisePropertyChanged("OthersJoinClausek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OthersSelectColumns>k__BackingField", IsRequired=true)]
        public string[] OthersSelectColumnsk__BackingField {
            get {
                return this.OthersSelectColumnsk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.OthersSelectColumnsk__BackingFieldField, value) != true)) {
                    this.OthersSelectColumnsk__BackingFieldField = value;
                    this.RaisePropertyChanged("OthersSelectColumnsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OthersTables>k__BackingField", IsRequired=true)]
        public string[] OthersTablesk__BackingField {
            get {
                return this.OthersTablesk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.OthersTablesk__BackingFieldField, value) != true)) {
                    this.OthersTablesk__BackingFieldField = value;
                    this.RaisePropertyChanged("OthersTablesk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OthersWhereClause>k__BackingField", IsRequired=true)]
        public string[] OthersWhereClausek__BackingField {
            get {
                return this.OthersWhereClausek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.OthersWhereClausek__BackingFieldField, value) != true)) {
                    this.OthersWhereClausek__BackingFieldField = value;
                    this.RaisePropertyChanged("OthersWhereClausek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SelectColumns>k__BackingField", IsRequired=true)]
        public string SelectColumnsk__BackingField {
            get {
                return this.SelectColumnsk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectColumnsk__BackingFieldField, value) != true)) {
                    this.SelectColumnsk__BackingFieldField = value;
                    this.RaisePropertyChanged("SelectColumnsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UseForeign>k__BackingField", IsRequired=true)]
        public Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.useForeignEnum UseForeignk__BackingField {
            get {
                return this.UseForeignk__BackingFieldField;
            }
            set {
                if ((this.UseForeignk__BackingFieldField.Equals(value) != true)) {
                    this.UseForeignk__BackingFieldField = value;
                    this.RaisePropertyChanged("UseForeignk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDataClass", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2Campi))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2ModelliT))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2CampiProprieta))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2CampiScript))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2ModelliScript))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2ModelliD))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.IstanzeDyn2Dati))]
    public partial class BaseDataClass : Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.DataClass {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dyn2Campi", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Data")]
    [System.SerializableAttribute()]
    public partial class Dyn2Campi : Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.BaseDataClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EtichettaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FkD2bcIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdcomuneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomecampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ObbligatorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoftwareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipodatoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Etichetta {
            get {
                return this.EtichettaField;
            }
            set {
                if ((object.ReferenceEquals(this.EtichettaField, value) != true)) {
                    this.EtichettaField = value;
                    this.RaisePropertyChanged("Etichetta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FkD2bcId {
            get {
                return this.FkD2bcIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FkD2bcIdField, value) != true)) {
                    this.FkD2bcIdField = value;
                    this.RaisePropertyChanged("FkD2bcId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idcomune {
            get {
                return this.IdcomuneField;
            }
            set {
                if ((object.ReferenceEquals(this.IdcomuneField, value) != true)) {
                    this.IdcomuneField = value;
                    this.RaisePropertyChanged("Idcomune");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nomecampo {
            get {
                return this.NomecampoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomecampoField, value) != true)) {
                    this.NomecampoField = value;
                    this.RaisePropertyChanged("Nomecampo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Obbligatorio {
            get {
                return this.ObbligatorioField;
            }
            set {
                if ((this.ObbligatorioField.Equals(value) != true)) {
                    this.ObbligatorioField = value;
                    this.RaisePropertyChanged("Obbligatorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Software {
            get {
                return this.SoftwareField;
            }
            set {
                if ((object.ReferenceEquals(this.SoftwareField, value) != true)) {
                    this.SoftwareField = value;
                    this.RaisePropertyChanged("Software");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipodato {
            get {
                return this.TipodatoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipodatoField, value) != true)) {
                    this.TipodatoField = value;
                    this.RaisePropertyChanged("Tipodato");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dyn2ModelliT", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Data")]
    [System.SerializableAttribute()]
    public partial class Dyn2ModelliT : Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.BaseDataClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceSchedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FkD2bcIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FlgReadonlyWebField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FlgStoricizzaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdcomuneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ModellomultiploField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScriptcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoftwareField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceScheda {
            get {
                return this.CodiceSchedaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceSchedaField, value) != true)) {
                    this.CodiceSchedaField = value;
                    this.RaisePropertyChanged("CodiceScheda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FkD2bcId {
            get {
                return this.FkD2bcIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FkD2bcIdField, value) != true)) {
                    this.FkD2bcIdField = value;
                    this.RaisePropertyChanged("FkD2bcId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FlgReadonlyWeb {
            get {
                return this.FlgReadonlyWebField;
            }
            set {
                if ((this.FlgReadonlyWebField.Equals(value) != true)) {
                    this.FlgReadonlyWebField = value;
                    this.RaisePropertyChanged("FlgReadonlyWeb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FlgStoricizza {
            get {
                return this.FlgStoricizzaField;
            }
            set {
                if ((this.FlgStoricizzaField.Equals(value) != true)) {
                    this.FlgStoricizzaField = value;
                    this.RaisePropertyChanged("FlgStoricizza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idcomune {
            get {
                return this.IdcomuneField;
            }
            set {
                if ((object.ReferenceEquals(this.IdcomuneField, value) != true)) {
                    this.IdcomuneField = value;
                    this.RaisePropertyChanged("Idcomune");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Modellomultiplo {
            get {
                return this.ModellomultiploField;
            }
            set {
                if ((this.ModellomultiploField.Equals(value) != true)) {
                    this.ModellomultiploField = value;
                    this.RaisePropertyChanged("Modellomultiplo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Scriptcode {
            get {
                return this.ScriptcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ScriptcodeField, value) != true)) {
                    this.ScriptcodeField = value;
                    this.RaisePropertyChanged("Scriptcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Software {
            get {
                return this.SoftwareField;
            }
            set {
                if ((object.ReferenceEquals(this.SoftwareField, value) != true)) {
                    this.SoftwareField = value;
                    this.RaisePropertyChanged("Software");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dyn2CampiProprieta", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Data")]
    [System.SerializableAttribute()]
    public partial class Dyn2CampiProprieta : Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.BaseDataClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FkD2cIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdcomuneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProprietaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValoreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FkD2cId {
            get {
                return this.FkD2cIdField;
            }
            set {
                if ((this.FkD2cIdField.Equals(value) != true)) {
                    this.FkD2cIdField = value;
                    this.RaisePropertyChanged("FkD2cId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idcomune {
            get {
                return this.IdcomuneField;
            }
            set {
                if ((object.ReferenceEquals(this.IdcomuneField, value) != true)) {
                    this.IdcomuneField = value;
                    this.RaisePropertyChanged("Idcomune");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proprieta {
            get {
                return this.ProprietaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProprietaField, value) != true)) {
                    this.ProprietaField = value;
                    this.RaisePropertyChanged("Proprieta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valore {
            get {
                return this.ValoreField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoreField, value) != true)) {
                    this.ValoreField = value;
                    this.RaisePropertyChanged("Valore");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dyn2CampiScript", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Data")]
    [System.SerializableAttribute()]
    public partial class Dyn2CampiScript : Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.BaseDataClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FkD2cIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdcomuneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ScriptField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Evento {
            get {
                return this.EventoField;
            }
            set {
                if ((object.ReferenceEquals(this.EventoField, value) != true)) {
                    this.EventoField = value;
                    this.RaisePropertyChanged("Evento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FkD2cId {
            get {
                return this.FkD2cIdField;
            }
            set {
                if ((this.FkD2cIdField.Equals(value) != true)) {
                    this.FkD2cIdField = value;
                    this.RaisePropertyChanged("FkD2cId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idcomune {
            get {
                return this.IdcomuneField;
            }
            set {
                if ((object.ReferenceEquals(this.IdcomuneField, value) != true)) {
                    this.IdcomuneField = value;
                    this.RaisePropertyChanged("Idcomune");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Script {
            get {
                return this.ScriptField;
            }
            set {
                if ((object.ReferenceEquals(this.ScriptField, value) != true)) {
                    this.ScriptField = value;
                    this.RaisePropertyChanged("Script");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dyn2ModelliScript", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Data")]
    [System.SerializableAttribute()]
    public partial class Dyn2ModelliScript : Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.BaseDataClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FkD2mtIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdcomuneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ScriptField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Evento {
            get {
                return this.EventoField;
            }
            set {
                if ((object.ReferenceEquals(this.EventoField, value) != true)) {
                    this.EventoField = value;
                    this.RaisePropertyChanged("Evento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FkD2mtId {
            get {
                return this.FkD2mtIdField;
            }
            set {
                if ((this.FkD2mtIdField.Equals(value) != true)) {
                    this.FkD2mtIdField = value;
                    this.RaisePropertyChanged("FkD2mtId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idcomune {
            get {
                return this.IdcomuneField;
            }
            set {
                if ((object.ReferenceEquals(this.IdcomuneField, value) != true)) {
                    this.IdcomuneField = value;
                    this.RaisePropertyChanged("Idcomune");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Script {
            get {
                return this.ScriptField;
            }
            set {
                if ((object.ReferenceEquals(this.ScriptField, value) != true)) {
                    this.ScriptField = value;
                    this.RaisePropertyChanged("Script");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dyn2ModelliD", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Data")]
    [System.SerializableAttribute()]
    public partial class Dyn2ModelliD : Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.BaseDataClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FkD2cIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FkD2mdtIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FkD2mtIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FlgMultiploField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FlgSpezzaTabellaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdcomuneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PosorizzontaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PosverticaleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FkD2cId {
            get {
                return this.FkD2cIdField;
            }
            set {
                if ((this.FkD2cIdField.Equals(value) != true)) {
                    this.FkD2cIdField = value;
                    this.RaisePropertyChanged("FkD2cId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FkD2mdtId {
            get {
                return this.FkD2mdtIdField;
            }
            set {
                if ((this.FkD2mdtIdField.Equals(value) != true)) {
                    this.FkD2mdtIdField = value;
                    this.RaisePropertyChanged("FkD2mdtId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FkD2mtId {
            get {
                return this.FkD2mtIdField;
            }
            set {
                if ((this.FkD2mtIdField.Equals(value) != true)) {
                    this.FkD2mtIdField = value;
                    this.RaisePropertyChanged("FkD2mtId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FlgMultiplo {
            get {
                return this.FlgMultiploField;
            }
            set {
                if ((this.FlgMultiploField.Equals(value) != true)) {
                    this.FlgMultiploField = value;
                    this.RaisePropertyChanged("FlgMultiplo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FlgSpezzaTabella {
            get {
                return this.FlgSpezzaTabellaField;
            }
            set {
                if ((this.FlgSpezzaTabellaField.Equals(value) != true)) {
                    this.FlgSpezzaTabellaField = value;
                    this.RaisePropertyChanged("FlgSpezzaTabella");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idcomune {
            get {
                return this.IdcomuneField;
            }
            set {
                if ((object.ReferenceEquals(this.IdcomuneField, value) != true)) {
                    this.IdcomuneField = value;
                    this.RaisePropertyChanged("Idcomune");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Posorizzontale {
            get {
                return this.PosorizzontaleField;
            }
            set {
                if ((this.PosorizzontaleField.Equals(value) != true)) {
                    this.PosorizzontaleField = value;
                    this.RaisePropertyChanged("Posorizzontale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Posverticale {
            get {
                return this.PosverticaleField;
            }
            set {
                if ((this.PosverticaleField.Equals(value) != true)) {
                    this.PosverticaleField = value;
                    this.RaisePropertyChanged("Posverticale");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="useForeignEnum", Namespace="http://schemas.datacontract.org/2004/07/PersonalLib2.Sql")]
    public enum useForeignEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Recoursive = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetModelliDinamiciDaInterventoEEndoRequest", Namespace="http://schemas.datacontract.org/2004/07/Sigepro.net.WebServices.WsAreaRiservata.W" +
        "cfServices.DatiDinamici")]
    [System.SerializableAttribute()]
    public partial class GetModelliDinamiciDaInterventoEEndoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodiceInterventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IgnoraTipiLocalizzazioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ListaEndoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ListaTipiLocalizzazioniField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodiceIntervento {
            get {
                return this.CodiceInterventoField;
            }
            set {
                if ((this.CodiceInterventoField.Equals(value) != true)) {
                    this.CodiceInterventoField = value;
                    this.RaisePropertyChanged("CodiceIntervento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IgnoraTipiLocalizzazione {
            get {
                return this.IgnoraTipiLocalizzazioneField;
            }
            set {
                if ((this.IgnoraTipiLocalizzazioneField.Equals(value) != true)) {
                    this.IgnoraTipiLocalizzazioneField = value;
                    this.RaisePropertyChanged("IgnoraTipiLocalizzazione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ListaEndo {
            get {
                return this.ListaEndoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaEndoField, value) != true)) {
                    this.ListaEndoField = value;
                    this.RaisePropertyChanged("ListaEndo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ListaTipiLocalizzazioni {
            get {
                return this.ListaTipiLocalizzazioniField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaTipiLocalizzazioniField, value) != true)) {
                    this.ListaTipiLocalizzazioniField = value;
                    this.RaisePropertyChanged("ListaTipiLocalizzazioni");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StrutturaModelloDinamicoDto", Namespace="http://schemas.datacontract.org/2004/07/Sigepro.net.WebServices.WsAreaRiservata.W" +
        "cfServices.DatiDinamici")]
    [System.SerializableAttribute()]
    public partial class StrutturaModelloDinamicoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2Campi[] CampiDinamiciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2ModelliT ModelloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2CampiProprieta[] ProprietaCampiDinamiciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2CampiScript[] ScriptsCampiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2ModelliScript[] ScriptsModelloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2ModelliD[] StrutturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Init.SIGePro.Manager.DTO.DatiDinamici.Dyn2TestoModello[] TestiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2Campi[] CampiDinamici {
            get {
                return this.CampiDinamiciField;
            }
            set {
                if ((object.ReferenceEquals(this.CampiDinamiciField, value) != true)) {
                    this.CampiDinamiciField = value;
                    this.RaisePropertyChanged("CampiDinamici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2ModelliT Modello {
            get {
                return this.ModelloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelloField, value) != true)) {
                    this.ModelloField = value;
                    this.RaisePropertyChanged("Modello");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2CampiProprieta[] ProprietaCampiDinamici {
            get {
                return this.ProprietaCampiDinamiciField;
            }
            set {
                if ((object.ReferenceEquals(this.ProprietaCampiDinamiciField, value) != true)) {
                    this.ProprietaCampiDinamiciField = value;
                    this.RaisePropertyChanged("ProprietaCampiDinamici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2CampiScript[] ScriptsCampi {
            get {
                return this.ScriptsCampiField;
            }
            set {
                if ((object.ReferenceEquals(this.ScriptsCampiField, value) != true)) {
                    this.ScriptsCampiField = value;
                    this.RaisePropertyChanged("ScriptsCampi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2ModelliScript[] ScriptsModello {
            get {
                return this.ScriptsModelloField;
            }
            set {
                if ((object.ReferenceEquals(this.ScriptsModelloField, value) != true)) {
                    this.ScriptsModelloField = value;
                    this.RaisePropertyChanged("ScriptsModello");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.Dyn2ModelliD[] Struttura {
            get {
                return this.StrutturaField;
            }
            set {
                if ((object.ReferenceEquals(this.StrutturaField, value) != true)) {
                    this.StrutturaField = value;
                    this.RaisePropertyChanged("Struttura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Init.SIGePro.Manager.DTO.DatiDinamici.Dyn2TestoModello[] Testi {
            get {
                return this.TestiField;
            }
            set {
                if ((object.ReferenceEquals(this.TestiField, value) != true)) {
                    this.TestiField = value;
                    this.RaisePropertyChanged("Testi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsVbgDatiDinamici.IWsDatiDinamici")]
    public interface IWsDatiDinamici {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsDatiDinamici/GetCompletionListRicerchePlus", ReplyAction="http://tempuri.org/IWsDatiDinamici/GetCompletionListRicerchePlusResponse")]
        Init.SIGePro.Manager.DTO.DatiDinamici.RisultatoRicercaDatiDinamiciDto[] GetCompletionListRicerchePlus(string token, int idCampo, string partial, Init.SIGePro.Manager.DTO.DatiDinamici.ValoreFiltroRicercaDto[] filtri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsDatiDinamici/GetDyn2DatiByCodiceIstanza", ReplyAction="http://tempuri.org/IWsDatiDinamici/GetDyn2DatiByCodiceIstanzaResponse")]
        Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.IstanzeDyn2Dati[] GetDyn2DatiByCodiceIstanza(string token, int codiceIstanza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsDatiDinamici/GetDyn2DatiByIdModello", ReplyAction="http://tempuri.org/IWsDatiDinamici/GetDyn2DatiByIdModelloResponse")]
        Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.IstanzeDyn2Dati[] GetDyn2DatiByIdModello(string token, int codiceIstanza, int idModello, int indiceCampo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsDatiDinamici/GetModelliDinamiciDaInterventoEEndo", ReplyAction="http://tempuri.org/IWsDatiDinamici/GetModelliDinamiciDaInterventoEEndoResponse")]
        Init.SIGePro.Manager.DTO.DatiDinamici.ListaModelliDinamiciDomandaDto GetModelliDinamiciDaInterventoEEndo(string token, Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.GetModelliDinamiciDaInterventoEEndoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsDatiDinamici/GetStrutturaModelloDinamico", ReplyAction="http://tempuri.org/IWsDatiDinamici/GetStrutturaModelloDinamicoResponse")]
        Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.StrutturaModelloDinamicoDto GetStrutturaModelloDinamico(string token, int idModello);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsDatiDinamici/InitializeControlRicerchePlus", ReplyAction="http://tempuri.org/IWsDatiDinamici/InitializeControlRicerchePlusResponse")]
        Init.SIGePro.Manager.DTO.DatiDinamici.RisultatoRicercaDatiDinamiciDto InitializeControlRicerchePlus(string token, int idCampo, string valore);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsDatiDinamici/RecuperaDocumentiIstanzaCollegata", ReplyAction="http://tempuri.org/IWsDatiDinamici/RecuperaDocumentiIstanzaCollegataResponse")]
        void RecuperaDocumentiIstanzaCollegata(string token, int codiceIstanzaOrigine, int idDomandaDestinazione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsDatiDinamici/GetDecodificheAttive", ReplyAction="http://tempuri.org/IWsDatiDinamici/GetDecodificheAttiveResponse")]
        Init.SIGePro.Manager.DTO.DatiDinamici.DecodificaDto[] GetDecodificheAttive(string token, string tabella);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsDatiDinamiciChannel : Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.IWsDatiDinamici, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsDatiDinamiciClient : System.ServiceModel.ClientBase<Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.IWsDatiDinamici>, Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.IWsDatiDinamici {
        
        public WsDatiDinamiciClient() {
        }
        
        public WsDatiDinamiciClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsDatiDinamiciClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsDatiDinamiciClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsDatiDinamiciClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Init.SIGePro.Manager.DTO.DatiDinamici.RisultatoRicercaDatiDinamiciDto[] GetCompletionListRicerchePlus(string token, int idCampo, string partial, Init.SIGePro.Manager.DTO.DatiDinamici.ValoreFiltroRicercaDto[] filtri) {
            return base.Channel.GetCompletionListRicerchePlus(token, idCampo, partial, filtri);
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.IstanzeDyn2Dati[] GetDyn2DatiByCodiceIstanza(string token, int codiceIstanza) {
            return base.Channel.GetDyn2DatiByCodiceIstanza(token, codiceIstanza);
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.IstanzeDyn2Dati[] GetDyn2DatiByIdModello(string token, int codiceIstanza, int idModello, int indiceCampo) {
            return base.Channel.GetDyn2DatiByIdModello(token, codiceIstanza, idModello, indiceCampo);
        }
        
        public Init.SIGePro.Manager.DTO.DatiDinamici.ListaModelliDinamiciDomandaDto GetModelliDinamiciDaInterventoEEndo(string token, Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.GetModelliDinamiciDaInterventoEEndoRequest request) {
            return base.Channel.GetModelliDinamiciDaInterventoEEndo(token, request);
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.WsVbgDatiDinamici.StrutturaModelloDinamicoDto GetStrutturaModelloDinamico(string token, int idModello) {
            return base.Channel.GetStrutturaModelloDinamico(token, idModello);
        }
        
        public Init.SIGePro.Manager.DTO.DatiDinamici.RisultatoRicercaDatiDinamiciDto InitializeControlRicerchePlus(string token, int idCampo, string valore) {
            return base.Channel.InitializeControlRicerchePlus(token, idCampo, valore);
        }
        
        public void RecuperaDocumentiIstanzaCollegata(string token, int codiceIstanzaOrigine, int idDomandaDestinazione) {
            base.Channel.RecuperaDocumentiIstanzaCollegata(token, codiceIstanzaOrigine, idDomandaDestinazione);
        }
        
        public Init.SIGePro.Manager.DTO.DatiDinamici.DecodificaDto[] GetDecodificheAttive(string token, string tabella) {
            return base.Channel.GetDecodificheAttive(token, tabella);
        }
    }
}
