//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.Sigepro.FrontEnd.AppLogic.WsEndoprocedimenti {
    using System.Runtime.Serialization;
    using System;
    using Init.SIGePro.Manager.DTO.Endoprocedimenti;
    using Init.SIGePro.Manager.DTO.Common;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsEndoprocedimenti.IWsEndoprocedimenti")]
    public interface IWsEndoprocedimenti {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEndoprocedimenti/GetEndoprocedimentiIncompatibili", ReplyAction="http://tempuri.org/IWsEndoprocedimenti/GetEndoprocedimentiIncompatibiliResponse")]
        EndoprocedimentoIncompatibileDto[] GetEndoprocedimentiIncompatibili(string token, int[] listaIdEndoAttivati);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEndoprocedimenti/GetEndoprocedimentoById", ReplyAction="http://tempuri.org/IWsEndoprocedimenti/GetEndoprocedimentoByIdResponse")]
        EndoprocedimentoDto GetEndoprocedimentoById(string token, int codiceEndo, AmbitoRicerca ambitoRicercaDocumenti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEndoprocedimenti/GetEndoprocedimentoDaIdMappatura", ReplyAction="http://tempuri.org/IWsEndoprocedimenti/GetEndoprocedimentoDaIdMappaturaResponse")]
        EndoprocedimentoMappatoDto GetEndoprocedimentoDaIdMappatura(string token, string codiceEndoRemoto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEndoprocedimenti/GetListaEndoDaIdIntervento", ReplyAction="http://tempuri.org/IWsEndoprocedimenti/GetListaEndoDaIdInterventoResponse")]
        EndoprocedimentiAreaRiservataDto GetListaEndoDaIdIntervento(string token, string codiceComune, int codiceIntervento, bool utenteTester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEndoprocedimenti/GetNaturaBaseDaidEndoprocedimento", ReplyAction="http://tempuri.org/IWsEndoprocedimenti/GetNaturaBaseDaidEndoprocedimentoResponse")]
        NaturaBaseEndoprocedimentoDto GetNaturaBaseDaidEndoprocedimento(string token, int idEndoprocedimento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEndoprocedimenti/GetTipiTitoloEndoDaListaCodiciInventario", ReplyAction="http://tempuri.org/IWsEndoprocedimenti/GetTipiTitoloEndoDaListaCodiciInventarioRe" +
            "sponse")]
        TipiTitoloPerCodiceInventario[] GetTipiTitoloEndoDaListaCodiciInventario(string token, int[] listaCodiciInventario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEndoprocedimenti/GetTipoTitoloById", ReplyAction="http://tempuri.org/IWsEndoprocedimenti/GetTipoTitoloByIdResponse")]
        TipiTitoloDto GetTipoTitoloById(string token, int codiceTipoTitolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsEndoprocedimenti/GetAllegatiEndoprocedimentiAreaRiservata", ReplyAction="http://tempuri.org/IWsEndoprocedimenti/GetAllegatiEndoprocedimentiAreaRiservataRe" +
            "sponse")]
        AllegatiPerEndoprocedimentoDto[] GetAllegatiEndoprocedimentiAreaRiservata(string token, int[] codiciEndoSelezionati);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsEndoprocedimentiChannel : Init.Sigepro.FrontEnd.AppLogic.WsEndoprocedimenti.IWsEndoprocedimenti, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsEndoprocedimentiClient : System.ServiceModel.ClientBase<Init.Sigepro.FrontEnd.AppLogic.WsEndoprocedimenti.IWsEndoprocedimenti>, Init.Sigepro.FrontEnd.AppLogic.WsEndoprocedimenti.IWsEndoprocedimenti {
        
        public WsEndoprocedimentiClient() {
        }
        
        public WsEndoprocedimentiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsEndoprocedimentiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsEndoprocedimentiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsEndoprocedimentiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EndoprocedimentoIncompatibileDto[] GetEndoprocedimentiIncompatibili(string token, int[] listaIdEndoAttivati) {
            return base.Channel.GetEndoprocedimentiIncompatibili(token, listaIdEndoAttivati);
        }
        
        public EndoprocedimentoDto GetEndoprocedimentoById(string token, int codiceEndo, AmbitoRicerca ambitoRicercaDocumenti) {
            return base.Channel.GetEndoprocedimentoById(token, codiceEndo, ambitoRicercaDocumenti);
        }
        
        public EndoprocedimentoMappatoDto GetEndoprocedimentoDaIdMappatura(string token, string codiceEndoRemoto) {
            return base.Channel.GetEndoprocedimentoDaIdMappatura(token, codiceEndoRemoto);
        }
        
        public EndoprocedimentiAreaRiservataDto GetListaEndoDaIdIntervento(string token, string codiceComune, int codiceIntervento, bool utenteTester) {
            return base.Channel.GetListaEndoDaIdIntervento(token, codiceComune, codiceIntervento, utenteTester);
        }
        
        public NaturaBaseEndoprocedimentoDto GetNaturaBaseDaidEndoprocedimento(string token, int idEndoprocedimento) {
            return base.Channel.GetNaturaBaseDaidEndoprocedimento(token, idEndoprocedimento);
        }
        
        public TipiTitoloPerCodiceInventario[] GetTipiTitoloEndoDaListaCodiciInventario(string token, int[] listaCodiciInventario) {
            return base.Channel.GetTipiTitoloEndoDaListaCodiciInventario(token, listaCodiciInventario);
        }
        
        public TipiTitoloDto GetTipoTitoloById(string token, int codiceTipoTitolo) {
            return base.Channel.GetTipoTitoloById(token, codiceTipoTitolo);
        }
        
        public AllegatiPerEndoprocedimentoDto[] GetAllegatiEndoprocedimentiAreaRiservata(string token, int[] codiciEndoSelezionati) {
            return base.Channel.GetAllegatiEndoprocedimentiAreaRiservata(token, codiciEndoSelezionati);
        }
    }
}
