//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gruppoinit.it/sigepro/definitions/oggetti", ConfigurationName="GestioneOggettiService.Oggetti")]
    public interface Oggetti {
        
        // CODEGEN: Generating message contract since the operation OggettiInsertV2 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="oggettiInsertV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertV2Response OggettiInsertV2(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertV2 request);
        
        // CODEGEN: Generating message contract since the operation OggettiUpdate is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="oggettiUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiUpdateResponse1 OggettiUpdate(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiUpdate request);
        
        // CODEGEN: Generating message contract since the operation OggettiDelete is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="oggettiDelete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiDeleteResponse1 OggettiDelete(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiDelete request);
        
        // CODEGEN: Generating message contract since the operation OggettiFind is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="oggettiFind", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindResponse1 OggettiFind(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFind request);
        
        // CODEGEN: Generating message contract since the operation OggettiInsert is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="oggettiInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertResponse1 OggettiInsert(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsert request);
        
        // CODEGEN: Generating message contract since the operation OggettiFindMetadati is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="OggettiFindMetadati", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindMetadatiResponse OggettiFindMetadati(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindMetadati request);
        
        // CODEGEN: Generating message contract since the operation OggettiFindByUid is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="oggettiFindByUid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindByUidResponse OggettiFindByUid(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindByUid request);
        
        // CODEGEN: Generating message contract since the operation OggettiFindNome is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="oggettiFindNome", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindNomeResponse1 OggettiFindNome(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindNome request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti")]
    public partial class OggettiInsertV2Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string fileNameField;
        
        private string mimeTypeField;
        
        private byte[] binaryDataField;
        
        private MetadatoType[] metadatiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("mimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] binaryData {
            get {
                return this.binaryDataField;
            }
            set {
                this.binaryDataField = value;
                this.RaisePropertyChanged("binaryData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("metadati", IsNullable=true, Order=4)]
        public MetadatoType[] metadati {
            get {
                return this.metadatiField;
            }
            set {
                this.metadatiField = value;
                this.RaisePropertyChanged("metadati");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti")]
    public partial class MetadatoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string chiaveField;
        
        private string valoreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string chiave {
            get {
                return this.chiaveField;
            }
            set {
                this.chiaveField = value;
                this.RaisePropertyChanged("chiave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string valore {
            get {
                return this.valoreField;
            }
            set {
                this.valoreField = value;
                this.RaisePropertyChanged("valore");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti")]
    public partial class OggettiInsertResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OggettiInsertV2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti", Order=0)]
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertV2Request OggettiInsertV2Request;
        
        public OggettiInsertV2() {
        }
        
        public OggettiInsertV2(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertV2Request OggettiInsertV2Request) {
            this.OggettiInsertV2Request = OggettiInsertV2Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OggettiInsertV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti", Order=0)]
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertResponse OggettiInsertResponse;
        
        public OggettiInsertV2Response() {
        }
        
        public OggettiInsertV2Response(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertResponse OggettiInsertResponse) {
            this.OggettiInsertResponse = OggettiInsertResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti")]
    public partial class OggettiUpdateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string idField;
        
        private string fileNameField;
        
        private string mimeTypeField;
        
        private byte[] binaryDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("mimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=4)]
        public byte[] binaryData {
            get {
                return this.binaryDataField;
            }
            set {
                this.binaryDataField = value;
                this.RaisePropertyChanged("binaryData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti")]
    public partial class OggettiUpdateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OggettiUpdate {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti", Order=0)]
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiUpdateRequest OggettiUpdateRequest;
        
        public OggettiUpdate() {
        }
        
        public OggettiUpdate(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiUpdateRequest OggettiUpdateRequest) {
            this.OggettiUpdateRequest = OggettiUpdateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OggettiUpdateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti", Order=0)]
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiUpdateResponse OggettiUpdateResponse;
        
        public OggettiUpdateResponse1() {
        }
        
        public OggettiUpdateResponse1(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiUpdateResponse OggettiUpdateResponse) {
            this.OggettiUpdateResponse = OggettiUpdateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti")]
    public partial class OggettiDeleteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti")]
    public partial class OggettiDeleteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OggettiDelete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti", Order=0)]
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiDeleteRequest OggettiDeleteRequest;
        
        public OggettiDelete() {
        }
        
        public OggettiDelete(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiDeleteRequest OggettiDeleteRequest) {
            this.OggettiDeleteRequest = OggettiDeleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OggettiDeleteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti", Order=0)]
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiDeleteResponse OggettiDeleteResponse;
        
        public OggettiDeleteResponse1() {
        }
        
        public OggettiDeleteResponse1(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiDeleteResponse OggettiDeleteResponse) {
            this.OggettiDeleteResponse = OggettiDeleteResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti")]
    public partial class OggettiFindRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti")]
    public partial class OggettiFindResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private string mimeTypeField;
        
        private byte[] binaryDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("mimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] binaryData {
            get {
                return this.binaryDataField;
            }
            set {
                this.binaryDataField = value;
                this.RaisePropertyChanged("binaryData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OggettiFind {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti", Order=0)]
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindRequest OggettiFindRequest;
        
        public OggettiFind() {
        }
        
        public OggettiFind(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindRequest OggettiFindRequest) {
            this.OggettiFindRequest = OggettiFindRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OggettiFindResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti", Order=0)]
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindResponse OggettiFindResponse;
        
        public OggettiFindResponse1() {
        }
        
        public OggettiFindResponse1(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindResponse OggettiFindResponse) {
            this.OggettiFindResponse = OggettiFindResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti")]
    public partial class OggettiInsertRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string fileNameField;
        
        private string mimeTypeField;
        
        private byte[] binaryDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("mimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] binaryData {
            get {
                return this.binaryDataField;
            }
            set {
                this.binaryDataField = value;
                this.RaisePropertyChanged("binaryData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OggettiInsert {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti", Order=0)]
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertRequest OggettiInsertRequest;
        
        public OggettiInsert() {
        }
        
        public OggettiInsert(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertRequest OggettiInsertRequest) {
            this.OggettiInsertRequest = OggettiInsertRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OggettiInsertResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti", Order=0)]
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertResponse OggettiInsertResponse;
        
        public OggettiInsertResponse1() {
        }
        
        public OggettiInsertResponse1(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertResponse OggettiInsertResponse) {
            this.OggettiInsertResponse = OggettiInsertResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti")]
    public partial class OggettiFindMetadatiRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string codiceIstanzaField;
        
        private MetadatoType[] metadatiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string codiceIstanza {
            get {
                return this.codiceIstanzaField;
            }
            set {
                this.codiceIstanzaField = value;
                this.RaisePropertyChanged("codiceIstanza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("metadati", Order=2)]
        public MetadatoType[] metadati {
            get {
                return this.metadatiField;
            }
            set {
                this.metadatiField = value;
                this.RaisePropertyChanged("metadati");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OggettiFindMetadati {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti", Order=0)]
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindMetadatiRequest OggettiFindMetadatiRequest;
        
        public OggettiFindMetadati() {
        }
        
        public OggettiFindMetadati(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindMetadatiRequest OggettiFindMetadatiRequest) {
            this.OggettiFindMetadatiRequest = OggettiFindMetadatiRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OggettiFindMetadatiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OggettiFindMetadatiResponse", Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("codiciOggetto", DataType="integer")]
        public string[] OggettiFindMetadatiResponse1;
        
        public OggettiFindMetadatiResponse() {
        }
        
        public OggettiFindMetadatiResponse(string[] OggettiFindMetadatiResponse1) {
            this.OggettiFindMetadatiResponse1 = OggettiFindMetadatiResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti")]
    public partial class OggettiFindByUidRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string uidField;
        
        private string softwareField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("uid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string software {
            get {
                return this.softwareField;
            }
            set {
                this.softwareField = value;
                this.RaisePropertyChanged("software");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OggettiFindByUid {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti", Order=0)]
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindByUidRequest OggettiFindByUidRequest;
        
        public OggettiFindByUid() {
        }
        
        public OggettiFindByUid(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindByUidRequest OggettiFindByUidRequest) {
            this.OggettiFindByUidRequest = OggettiFindByUidRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OggettiFindByUidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti", Order=0)]
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindResponse OggettiFindResponse;
        
        public OggettiFindByUidResponse() {
        }
        
        public OggettiFindByUidResponse(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindResponse OggettiFindResponse) {
            this.OggettiFindResponse = OggettiFindResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti")]
    public partial class OggettiFindNomeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti")]
    public partial class OggettiFindNomeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OggettiFindNome {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti", Order=0)]
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindNomeRequest OggettiFindNomeRequest;
        
        public OggettiFindNome() {
        }
        
        public OggettiFindNome(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindNomeRequest OggettiFindNomeRequest) {
            this.OggettiFindNomeRequest = OggettiFindNomeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OggettiFindNomeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://gruppoinit.it/sigepro/schemas/messages/oggetti", Order=0)]
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindNomeResponse OggettiFindNomeResponse;
        
        public OggettiFindNomeResponse1() {
        }
        
        public OggettiFindNomeResponse1(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindNomeResponse OggettiFindNomeResponse) {
            this.OggettiFindNomeResponse = OggettiFindNomeResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OggettiChannel : Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OggettiClient : System.ServiceModel.ClientBase<Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti>, Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti {
        
        public OggettiClient() {
        }
        
        public OggettiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OggettiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OggettiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OggettiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertV2Response Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti.OggettiInsertV2(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertV2 request) {
            return base.Channel.OggettiInsertV2(request);
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertResponse OggettiInsertV2(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertV2Request OggettiInsertV2Request) {
            Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertV2 inValue = new Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertV2();
            inValue.OggettiInsertV2Request = OggettiInsertV2Request;
            Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertV2Response retVal = ((Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti)(this)).OggettiInsertV2(inValue);
            return retVal.OggettiInsertResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiUpdateResponse1 Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti.OggettiUpdate(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiUpdate request) {
            return base.Channel.OggettiUpdate(request);
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiUpdateResponse OggettiUpdate(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiUpdateRequest OggettiUpdateRequest) {
            Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiUpdate inValue = new Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiUpdate();
            inValue.OggettiUpdateRequest = OggettiUpdateRequest;
            Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiUpdateResponse1 retVal = ((Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti)(this)).OggettiUpdate(inValue);
            return retVal.OggettiUpdateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiDeleteResponse1 Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti.OggettiDelete(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiDelete request) {
            return base.Channel.OggettiDelete(request);
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiDeleteResponse OggettiDelete(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiDeleteRequest OggettiDeleteRequest) {
            Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiDelete inValue = new Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiDelete();
            inValue.OggettiDeleteRequest = OggettiDeleteRequest;
            Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiDeleteResponse1 retVal = ((Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti)(this)).OggettiDelete(inValue);
            return retVal.OggettiDeleteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindResponse1 Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti.OggettiFind(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFind request) {
            return base.Channel.OggettiFind(request);
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindResponse OggettiFind(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindRequest OggettiFindRequest) {
            Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFind inValue = new Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFind();
            inValue.OggettiFindRequest = OggettiFindRequest;
            Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindResponse1 retVal = ((Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti)(this)).OggettiFind(inValue);
            return retVal.OggettiFindResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertResponse1 Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti.OggettiInsert(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsert request) {
            return base.Channel.OggettiInsert(request);
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertResponse OggettiInsert(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertRequest OggettiInsertRequest) {
            Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsert inValue = new Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsert();
            inValue.OggettiInsertRequest = OggettiInsertRequest;
            Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiInsertResponse1 retVal = ((Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti)(this)).OggettiInsert(inValue);
            return retVal.OggettiInsertResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindMetadatiResponse Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti.OggettiFindMetadati(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindMetadati request) {
            return base.Channel.OggettiFindMetadati(request);
        }
        
        public string[] OggettiFindMetadati(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindMetadatiRequest OggettiFindMetadatiRequest) {
            Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindMetadati inValue = new Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindMetadati();
            inValue.OggettiFindMetadatiRequest = OggettiFindMetadatiRequest;
            Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindMetadatiResponse retVal = ((Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti)(this)).OggettiFindMetadati(inValue);
            return retVal.OggettiFindMetadatiResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindByUidResponse Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti.OggettiFindByUid(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindByUid request) {
            return base.Channel.OggettiFindByUid(request);
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindResponse OggettiFindByUid(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindByUidRequest OggettiFindByUidRequest) {
            Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindByUid inValue = new Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindByUid();
            inValue.OggettiFindByUidRequest = OggettiFindByUidRequest;
            Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindByUidResponse retVal = ((Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti)(this)).OggettiFindByUid(inValue);
            return retVal.OggettiFindResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindNomeResponse1 Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti.OggettiFindNome(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindNome request) {
            return base.Channel.OggettiFindNome(request);
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindNomeResponse OggettiFindNome(Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindNomeRequest OggettiFindNomeRequest) {
            Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindNome inValue = new Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindNome();
            inValue.OggettiFindNomeRequest = OggettiFindNomeRequest;
            Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.OggettiFindNomeResponse1 retVal = ((Init.Sigepro.FrontEnd.AppLogic.GestioneOggettiService.Oggetti)(this)).OggettiFindNome(inValue);
            return retVal.OggettiFindNomeResponse;
        }
    }
}
