//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.Sigepro.FrontEnd.AppLogic.WsInterventi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlberoProcDocumentiCat", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Data")]
    [System.SerializableAttribute()]
    public partial class AlberoProcDocumentiCat : Init.Sigepro.FrontEnd.AppLogic.WsInterventi.BaseDataClass {
        
        private System.Nullable<int> m_codiceoggettoField;
        
        private string m_descrizioneField;
        
        private System.Nullable<int> m_fo_nonpermetteuploadField;
        
        private System.Nullable<int> m_fo_richiedefirmaField;
        
        private System.Nullable<int> m_idField;
        
        private string m_idcomuneField;
        
        private Init.Sigepro.FrontEnd.AppLogic.WsInterventi.Oggetti m_oggettoField;
        
        private System.Nullable<int> m_ordineField;
        
        private string m_softwareField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> m_codiceoggetto {
            get {
                return this.m_codiceoggettoField;
            }
            set {
                if ((this.m_codiceoggettoField.Equals(value) != true)) {
                    this.m_codiceoggettoField = value;
                    this.RaisePropertyChanged("m_codiceoggetto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_descrizione {
            get {
                return this.m_descrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.m_descrizioneField, value) != true)) {
                    this.m_descrizioneField = value;
                    this.RaisePropertyChanged("m_descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> m_fo_nonpermetteupload {
            get {
                return this.m_fo_nonpermetteuploadField;
            }
            set {
                if ((this.m_fo_nonpermetteuploadField.Equals(value) != true)) {
                    this.m_fo_nonpermetteuploadField = value;
                    this.RaisePropertyChanged("m_fo_nonpermetteupload");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> m_fo_richiedefirma {
            get {
                return this.m_fo_richiedefirmaField;
            }
            set {
                if ((this.m_fo_richiedefirmaField.Equals(value) != true)) {
                    this.m_fo_richiedefirmaField = value;
                    this.RaisePropertyChanged("m_fo_richiedefirma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> m_id {
            get {
                return this.m_idField;
            }
            set {
                if ((this.m_idField.Equals(value) != true)) {
                    this.m_idField = value;
                    this.RaisePropertyChanged("m_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_idcomune {
            get {
                return this.m_idcomuneField;
            }
            set {
                if ((object.ReferenceEquals(this.m_idcomuneField, value) != true)) {
                    this.m_idcomuneField = value;
                    this.RaisePropertyChanged("m_idcomune");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Init.Sigepro.FrontEnd.AppLogic.WsInterventi.Oggetti m_oggetto {
            get {
                return this.m_oggettoField;
            }
            set {
                if ((object.ReferenceEquals(this.m_oggettoField, value) != true)) {
                    this.m_oggettoField = value;
                    this.RaisePropertyChanged("m_oggetto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> m_ordine {
            get {
                return this.m_ordineField;
            }
            set {
                if ((this.m_ordineField.Equals(value) != true)) {
                    this.m_ordineField = value;
                    this.RaisePropertyChanged("m_ordine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_software {
            get {
                return this.m_softwareField;
            }
            set {
                if ((object.ReferenceEquals(this.m_softwareField, value) != true)) {
                    this.m_softwareField = value;
                    this.RaisePropertyChanged("m_software");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataClass", Namespace="http://schemas.datacontract.org/2004/07/PersonalLib2.Sql")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsInterventi.BaseDataClass))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsInterventi.Oggetti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsInterventi.AlberoProcDocumentiCat))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Init.SIGePro.Manager.DTO.Oneri.OnereDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Oneri.OnereDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Utils.ClassTree<Init.SIGePro.Manager.DTO.Interventi.InterventoDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Init.Utils.ClassTree<Init.SIGePro.Manager.DTO.Interventi.InterventoDto>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Init.SIGePro.Manager.DTO.AllegatiDomandaOnline.AllegatoInterventoDomandaOnlineDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.AllegatiDomandaOnline.AllegatoInterventoDomandaOnlineDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.AllegatiDomandaOnline.AllegatoInterventoDomandaOnlineDto.CategoriaAllegatoIntervento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Init.SIGePro.Manager.DTO.DatiDinamici.SchedaDinamicaDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.DatiDinamici.SchedaDinamicaDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.DatiDinamici.TipoFirmaEnum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.DatiDinamici.SchedaDinamicaInterventoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.DatiDinamici.SchedaDinamicaEndoprocedimentoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Init.SIGePro.Manager.DTO.Endoprocedimenti.FamigliaEndoprocedimentoDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Endoprocedimenti.FamigliaEndoprocedimentoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Init.SIGePro.Manager.DTO.Endoprocedimenti.TipoEndoprocedimentoDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Endoprocedimenti.TipoEndoprocedimentoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Init.SIGePro.Manager.DTO.Endoprocedimenti.EndoprocedimentoDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Endoprocedimenti.EndoprocedimentoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Init.SIGePro.Manager.DTO.Endoprocedimenti.AllegatoDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Endoprocedimenti.AllegatoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Init.SIGePro.Manager.DTO.Endoprocedimenti.TestiEstesiDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Endoprocedimenti.TestiEstesiDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Common.AmbitoRicerca))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Common.LivelloAutenticazioneBOEnum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Init.Sigepro.FrontEnd.AppLogic.WsInterventi.AlberoProcDocumentiCat>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsInterventi.RisultatoVerificaAccessoIntervento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Init.SIGePro.Manager.DTO.Procedure.FaseAttuativaDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Procedure.FaseAttuativaDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Init.SIGePro.Manager.DTO.Normative.NormativaDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Normative.NormativaDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Init.Sigepro.FrontEnd.AppLogic.WsInterventi.InterventoBreveDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsInterventi.InterventoBreveDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<int>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.BaseDto<int, string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Interventi.NodoAlberoInterventiDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Interventi.InterventoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Init.SIGePro.Manager.DTO.Interventi.DocumentoInterventoDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Interventi.DocumentoInterventoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Init.SIGePro.Manager.DTO.Interventi.InterventoDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsInterventi.useForeignEnum))]
    public partial class DataClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _orderByField;
        
        private System.Collections.Generic.List<object> _othersJoinClauseField;
        
        private System.Collections.Generic.List<object> _othersSelectColumnsField;
        
        private System.Collections.Generic.List<object> _othersTablesField;
        
        private System.Collections.Generic.List<object> _othersWhereClauseField;
        
        private string _selectColumnsField;
        
        private Init.Sigepro.FrontEnd.AppLogic.WsInterventi.useForeignEnum _useForeignField;
        
        private string m_dataTableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _orderBy {
            get {
                return this._orderByField;
            }
            set {
                if ((object.ReferenceEquals(this._orderByField, value) != true)) {
                    this._orderByField = value;
                    this.RaisePropertyChanged("_orderBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<object> _othersJoinClause {
            get {
                return this._othersJoinClauseField;
            }
            set {
                if ((object.ReferenceEquals(this._othersJoinClauseField, value) != true)) {
                    this._othersJoinClauseField = value;
                    this.RaisePropertyChanged("_othersJoinClause");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<object> _othersSelectColumns {
            get {
                return this._othersSelectColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this._othersSelectColumnsField, value) != true)) {
                    this._othersSelectColumnsField = value;
                    this.RaisePropertyChanged("_othersSelectColumns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<object> _othersTables {
            get {
                return this._othersTablesField;
            }
            set {
                if ((object.ReferenceEquals(this._othersTablesField, value) != true)) {
                    this._othersTablesField = value;
                    this.RaisePropertyChanged("_othersTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<object> _othersWhereClause {
            get {
                return this._othersWhereClauseField;
            }
            set {
                if ((object.ReferenceEquals(this._othersWhereClauseField, value) != true)) {
                    this._othersWhereClauseField = value;
                    this.RaisePropertyChanged("_othersWhereClause");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _selectColumns {
            get {
                return this._selectColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this._selectColumnsField, value) != true)) {
                    this._selectColumnsField = value;
                    this.RaisePropertyChanged("_selectColumns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Init.Sigepro.FrontEnd.AppLogic.WsInterventi.useForeignEnum _useForeign {
            get {
                return this._useForeignField;
            }
            set {
                if ((this._useForeignField.Equals(value) != true)) {
                    this._useForeignField = value;
                    this.RaisePropertyChanged("_useForeign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_dataTableName {
            get {
                return this.m_dataTableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.m_dataTableNameField, value) != true)) {
                    this.m_dataTableNameField = value;
                    this.RaisePropertyChanged("m_dataTableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDataClass", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsInterventi.Oggetti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsInterventi.AlberoProcDocumentiCat))]
    public partial class BaseDataClass : Init.Sigepro.FrontEnd.AppLogic.WsInterventi.DataClass {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Oggetti", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Data")]
    [System.SerializableAttribute()]
    public partial class Oggetti : Init.Sigepro.FrontEnd.AppLogic.WsInterventi.BaseDataClass {
        
        private string codiceoggettoField;
        
        private string idcomuneField;
        
        private string nomefileField;
        
        private byte[] oggettoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codiceoggetto {
            get {
                return this.codiceoggettoField;
            }
            set {
                if ((object.ReferenceEquals(this.codiceoggettoField, value) != true)) {
                    this.codiceoggettoField = value;
                    this.RaisePropertyChanged("codiceoggetto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string idcomune {
            get {
                return this.idcomuneField;
            }
            set {
                if ((object.ReferenceEquals(this.idcomuneField, value) != true)) {
                    this.idcomuneField = value;
                    this.RaisePropertyChanged("idcomune");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nomefile {
            get {
                return this.nomefileField;
            }
            set {
                if ((object.ReferenceEquals(this.nomefileField, value) != true)) {
                    this.nomefileField = value;
                    this.RaisePropertyChanged("nomefile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] oggetto {
            get {
                return this.oggettoField;
            }
            set {
                if ((object.ReferenceEquals(this.oggettoField, value) != true)) {
                    this.oggettoField = value;
                    this.RaisePropertyChanged("oggetto");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RisultatoVerificaAccessoIntervento", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Manager.Logic.Attraversament" +
        "oAlberoInterventi.VerificaAttivazione")]
    public enum RisultatoVerificaAccessoIntervento : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Accessibile = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NonPubblicato = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LivelloAutenticazioneNonSufficiente = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InterventoNonAttivo = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InterventoBreveDto", Namespace="http://schemas.datacontract.org/2004/07/Sigepro.net.WebServices.WsAreaRiservata.W" +
        "cfServices.Interventi")]
    [System.SerializableAttribute()]
    public partial class InterventoBreveDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codice {
            get {
                return this.CodiceField;
            }
            set {
                if ((this.CodiceField.Equals(value) != true)) {
                    this.CodiceField = value;
                    this.RaisePropertyChanged("Codice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="useForeignEnum", Namespace="http://schemas.datacontract.org/2004/07/PersonalLib2.Sql")]
    public enum useForeignEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Recoursive = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsInterventi.IWsInterventi")]
    public interface IWsInterventi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/GetAlberaturaDaIdNodo", ReplyAction="http://tempuri.org/IWsInterventi/GetAlberaturaDaIdNodoResponse")]
        Init.SIGePro.Manager.DTO.Interventi.NodoAlberoInterventiDto GetAlberaturaDaIdNodo(string token, int codiceIntervento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/GetCategorieAllegatiInterventoChePermettonoUploa" +
            "d", ReplyAction="http://tempuri.org/IWsInterventi/GetCategorieAllegatiInterventoChePermettonoUploa" +
            "dResponse")]
        System.Collections.Generic.List<Init.Sigepro.FrontEnd.AppLogic.WsInterventi.AlberoProcDocumentiCat> GetCategorieAllegatiInterventoChePermettonoUpload(string token, string software);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/GetCodiceOggettoWorkflowDaCodiceIntervento", ReplyAction="http://tempuri.org/IWsInterventi/GetCodiceOggettoWorkflowDaCodiceInterventoRespon" +
            "se")]
        System.Nullable<int> GetCodiceOggettoWorkflowDaCodiceIntervento(string token, int idIntervento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/GetDettagliIntervento", ReplyAction="http://tempuri.org/IWsInterventi/GetDettagliInterventoResponse")]
        Init.SIGePro.Manager.DTO.Interventi.InterventoDto GetDettagliIntervento(string token, int codiceIntervento, Init.SIGePro.Manager.DTO.Common.AmbitoRicerca ambitoRicercaDocumenti, bool leggiNoteEstese);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/GetDocumentiDaCodiceIntervento", ReplyAction="http://tempuri.org/IWsInterventi/GetDocumentiDaCodiceInterventoResponse")]
        System.Collections.Generic.List<Init.SIGePro.Manager.DTO.AllegatiDomandaOnline.AllegatoInterventoDomandaOnlineDto> GetDocumentiDaCodiceIntervento(string token, int codiceIntervento, Init.SIGePro.Manager.DTO.Common.AmbitoRicerca ambitoRicercaDocumenti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/GetIdCertificatoDiInvioDomandaDaIdIntervento", ReplyAction="http://tempuri.org/IWsInterventi/GetIdCertificatoDiInvioDomandaDaIdInterventoResp" +
            "onse")]
        System.Nullable<int> GetIdCertificatoDiInvioDomandaDaIdIntervento(string token, int idIntervento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/GetIdDrupalDaCodiceIntervento", ReplyAction="http://tempuri.org/IWsInterventi/GetIdDrupalDaCodiceInterventoResponse")]
        string GetIdDrupalDaCodiceIntervento(string token, int codiceIntervento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/GetIdRiepilogoDomandaDaIdIntervento", ReplyAction="http://tempuri.org/IWsInterventi/GetIdRiepilogoDomandaDaIdInterventoResponse")]
        System.Nullable<int> GetIdRiepilogoDomandaDaIdIntervento(string token, int idIntervento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/GetListaIdNodiPadreIntervento", ReplyAction="http://tempuri.org/IWsInterventi/GetListaIdNodiPadreInterventoResponse")]
        System.Collections.Generic.List<int> GetListaIdNodiPadreIntervento(string token, int codiceIntervento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/GetLivelloDiAccessoIntervento", ReplyAction="http://tempuri.org/IWsInterventi/GetLivelloDiAccessoInterventoResponse")]
        int GetLivelloDiAccessoIntervento(string token, int codiceIntervento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/GetSottonodiIntervento", ReplyAction="http://tempuri.org/IWsInterventi/GetSottonodiInterventoResponse")]
        System.Collections.Generic.List<Init.SIGePro.Manager.DTO.Interventi.InterventoDto> GetSottonodiIntervento(string token, string software, int idNodo, Init.SIGePro.Manager.DTO.Common.AmbitoRicerca ambitoRicerca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/GetSottonodiInterventoDaIdAteco", ReplyAction="http://tempuri.org/IWsInterventi/GetSottonodiInterventoDaIdAtecoResponse")]
        System.Collections.Generic.List<Init.SIGePro.Manager.DTO.Interventi.InterventoDto> GetSottonodiInterventoDaIdAteco(string token, string software, int idNodoPadre, int idAteco, Init.SIGePro.Manager.DTO.Common.AmbitoRicerca ambitoRicerca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/GetStrutturaAlberoInterventi", ReplyAction="http://tempuri.org/IWsInterventi/GetStrutturaAlberoInterventiResponse")]
        Init.SIGePro.Manager.DTO.Interventi.NodoAlberoInterventiDto GetStrutturaAlberoInterventi(string token, string software);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/HaPresentatoDomandePerIntervento", ReplyAction="http://tempuri.org/IWsInterventi/HaPresentatoDomandePerInterventoResponse")]
        bool HaPresentatoDomandePerIntervento(string token, int idIntervento, string codiceFiscaleRichiedente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/InterventoSupportaRedirect", ReplyAction="http://tempuri.org/IWsInterventi/InterventoSupportaRedirectResponse")]
        bool InterventoSupportaRedirect(string token, int idIntervento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/RicercaTestualeInterventi", ReplyAction="http://tempuri.org/IWsInterventi/RicercaTestualeInterventiResponse")]
        System.Collections.Generic.List<Init.Sigepro.FrontEnd.AppLogic.WsInterventi.InterventoBreveDto> RicercaTestualeInterventi(string token, string software, string matchParziale, int matchCount, string modoRicerca, string tipoRicerca, Init.SIGePro.Manager.DTO.Common.AmbitoRicerca ambitoRicerca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventi/VerificaAccessoIntervento", ReplyAction="http://tempuri.org/IWsInterventi/VerificaAccessoInterventoResponse")]
        Init.Sigepro.FrontEnd.AppLogic.WsInterventi.RisultatoVerificaAccessoIntervento VerificaAccessoIntervento(string token, Init.SIGePro.Manager.DTO.Common.LivelloAutenticazioneBOEnum livelloAutenticazione, int codiceIntervento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsInterventiChannel : Init.Sigepro.FrontEnd.AppLogic.WsInterventi.IWsInterventi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsInterventiClient : System.ServiceModel.ClientBase<Init.Sigepro.FrontEnd.AppLogic.WsInterventi.IWsInterventi>, Init.Sigepro.FrontEnd.AppLogic.WsInterventi.IWsInterventi {
        
        public WsInterventiClient() {
        }
        
        public WsInterventiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsInterventiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsInterventiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsInterventiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Init.SIGePro.Manager.DTO.Interventi.NodoAlberoInterventiDto GetAlberaturaDaIdNodo(string token, int codiceIntervento) {
            return base.Channel.GetAlberaturaDaIdNodo(token, codiceIntervento);
        }
        
        public System.Collections.Generic.List<Init.Sigepro.FrontEnd.AppLogic.WsInterventi.AlberoProcDocumentiCat> GetCategorieAllegatiInterventoChePermettonoUpload(string token, string software) {
            return base.Channel.GetCategorieAllegatiInterventoChePermettonoUpload(token, software);
        }
        
        public System.Nullable<int> GetCodiceOggettoWorkflowDaCodiceIntervento(string token, int idIntervento) {
            return base.Channel.GetCodiceOggettoWorkflowDaCodiceIntervento(token, idIntervento);
        }
        
        public Init.SIGePro.Manager.DTO.Interventi.InterventoDto GetDettagliIntervento(string token, int codiceIntervento, Init.SIGePro.Manager.DTO.Common.AmbitoRicerca ambitoRicercaDocumenti, bool leggiNoteEstese) {
            return base.Channel.GetDettagliIntervento(token, codiceIntervento, ambitoRicercaDocumenti, leggiNoteEstese);
        }
        
        public System.Collections.Generic.List<Init.SIGePro.Manager.DTO.AllegatiDomandaOnline.AllegatoInterventoDomandaOnlineDto> GetDocumentiDaCodiceIntervento(string token, int codiceIntervento, Init.SIGePro.Manager.DTO.Common.AmbitoRicerca ambitoRicercaDocumenti) {
            return base.Channel.GetDocumentiDaCodiceIntervento(token, codiceIntervento, ambitoRicercaDocumenti);
        }
        
        public System.Nullable<int> GetIdCertificatoDiInvioDomandaDaIdIntervento(string token, int idIntervento) {
            return base.Channel.GetIdCertificatoDiInvioDomandaDaIdIntervento(token, idIntervento);
        }
        
        public string GetIdDrupalDaCodiceIntervento(string token, int codiceIntervento) {
            return base.Channel.GetIdDrupalDaCodiceIntervento(token, codiceIntervento);
        }
        
        public System.Nullable<int> GetIdRiepilogoDomandaDaIdIntervento(string token, int idIntervento) {
            return base.Channel.GetIdRiepilogoDomandaDaIdIntervento(token, idIntervento);
        }
        
        public System.Collections.Generic.List<int> GetListaIdNodiPadreIntervento(string token, int codiceIntervento) {
            return base.Channel.GetListaIdNodiPadreIntervento(token, codiceIntervento);
        }
        
        public int GetLivelloDiAccessoIntervento(string token, int codiceIntervento) {
            return base.Channel.GetLivelloDiAccessoIntervento(token, codiceIntervento);
        }
        
        public System.Collections.Generic.List<Init.SIGePro.Manager.DTO.Interventi.InterventoDto> GetSottonodiIntervento(string token, string software, int idNodo, Init.SIGePro.Manager.DTO.Common.AmbitoRicerca ambitoRicerca) {
            return base.Channel.GetSottonodiIntervento(token, software, idNodo, ambitoRicerca);
        }
        
        public System.Collections.Generic.List<Init.SIGePro.Manager.DTO.Interventi.InterventoDto> GetSottonodiInterventoDaIdAteco(string token, string software, int idNodoPadre, int idAteco, Init.SIGePro.Manager.DTO.Common.AmbitoRicerca ambitoRicerca) {
            return base.Channel.GetSottonodiInterventoDaIdAteco(token, software, idNodoPadre, idAteco, ambitoRicerca);
        }
        
        public Init.SIGePro.Manager.DTO.Interventi.NodoAlberoInterventiDto GetStrutturaAlberoInterventi(string token, string software) {
            return base.Channel.GetStrutturaAlberoInterventi(token, software);
        }
        
        public bool HaPresentatoDomandePerIntervento(string token, int idIntervento, string codiceFiscaleRichiedente) {
            return base.Channel.HaPresentatoDomandePerIntervento(token, idIntervento, codiceFiscaleRichiedente);
        }
        
        public bool InterventoSupportaRedirect(string token, int idIntervento) {
            return base.Channel.InterventoSupportaRedirect(token, idIntervento);
        }
        
        public System.Collections.Generic.List<Init.Sigepro.FrontEnd.AppLogic.WsInterventi.InterventoBreveDto> RicercaTestualeInterventi(string token, string software, string matchParziale, int matchCount, string modoRicerca, string tipoRicerca, Init.SIGePro.Manager.DTO.Common.AmbitoRicerca ambitoRicerca) {
            return base.Channel.RicercaTestualeInterventi(token, software, matchParziale, matchCount, modoRicerca, tipoRicerca, ambitoRicerca);
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.WsInterventi.RisultatoVerificaAccessoIntervento VerificaAccessoIntervento(string token, Init.SIGePro.Manager.DTO.Common.LivelloAutenticazioneBOEnum livelloAutenticazione, int codiceIntervento) {
            return base.Channel.VerificaAccessoIntervento(token, livelloAutenticazione, codiceIntervento);
        }
    }
}
