//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.Sigepro.FrontEnd.AppLogic.WsUrlAccessoConsoleService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfigurazioneUrlConsole", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Manager.Logic.GestioneConsol" +
        "e.UrlAccesso")]
    [System.SerializableAttribute()]
    public partial class ConfigurazioneUrlConsole : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Init.Sigepro.FrontEnd.AppLogic.WsUrlAccessoConsoleService.UrlConsole DefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Init.Sigepro.FrontEnd.AppLogic.WsUrlAccessoConsoleService.UrlConsolePerComune[] UrlLocalizzatiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UrlLocalizzatiAttiviField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Init.Sigepro.FrontEnd.AppLogic.WsUrlAccessoConsoleService.UrlConsole Default {
            get {
                return this.DefaultField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultField, value) != true)) {
                    this.DefaultField = value;
                    this.RaisePropertyChanged("Default");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Init.Sigepro.FrontEnd.AppLogic.WsUrlAccessoConsoleService.UrlConsolePerComune[] UrlLocalizzati {
            get {
                return this.UrlLocalizzatiField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlLocalizzatiField, value) != true)) {
                    this.UrlLocalizzatiField = value;
                    this.RaisePropertyChanged("UrlLocalizzati");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UrlLocalizzatiAttivi {
            get {
                return this.UrlLocalizzatiAttiviField;
            }
            set {
                if ((this.UrlLocalizzatiAttiviField.Equals(value) != true)) {
                    this.UrlLocalizzatiAttiviField = value;
                    this.RaisePropertyChanged("UrlLocalizzatiAttivi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrlConsole", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Manager.Logic.GestioneConsol" +
        "e.UrlAccesso")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsUrlAccessoConsoleService.UrlConsolePerComune))]
    public partial class UrlConsole : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrossLoginUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlIstanzeInSospesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlNuovaDomandaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrossLoginUrl {
            get {
                return this.CrossLoginUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.CrossLoginUrlField, value) != true)) {
                    this.CrossLoginUrlField = value;
                    this.RaisePropertyChanged("CrossLoginUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlIstanzeInSospeso {
            get {
                return this.UrlIstanzeInSospesoField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlIstanzeInSospesoField, value) != true)) {
                    this.UrlIstanzeInSospesoField = value;
                    this.RaisePropertyChanged("UrlIstanzeInSospeso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlNuovaDomanda {
            get {
                return this.UrlNuovaDomandaField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlNuovaDomandaField, value) != true)) {
                    this.UrlNuovaDomandaField = value;
                    this.RaisePropertyChanged("UrlNuovaDomanda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrlConsolePerComune", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Manager.Logic.GestioneConsol" +
        "e.UrlAccesso")]
    [System.SerializableAttribute()]
    public partial class UrlConsolePerComune : Init.Sigepro.FrontEnd.AppLogic.WsUrlAccessoConsoleService.UrlConsole {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceComuneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodiceComune {
            get {
                return this.CodiceComuneField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceComuneField, value) != true)) {
                    this.CodiceComuneField = value;
                    this.RaisePropertyChanged("CodiceComune");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsUrlAccessoConsoleService.IWsUrlAccessoConsoleService")]
    public interface IWsUrlAccessoConsoleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsUrlAccessoConsoleService/GetUrlAccessoConsole", ReplyAction="http://tempuri.org/IWsUrlAccessoConsoleService/GetUrlAccessoConsoleResponse")]
        Init.Sigepro.FrontEnd.AppLogic.WsUrlAccessoConsoleService.ConfigurazioneUrlConsole GetUrlAccessoConsole(string token, string software);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsUrlAccessoConsoleServiceChannel : Init.Sigepro.FrontEnd.AppLogic.WsUrlAccessoConsoleService.IWsUrlAccessoConsoleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsUrlAccessoConsoleServiceClient : System.ServiceModel.ClientBase<Init.Sigepro.FrontEnd.AppLogic.WsUrlAccessoConsoleService.IWsUrlAccessoConsoleService>, Init.Sigepro.FrontEnd.AppLogic.WsUrlAccessoConsoleService.IWsUrlAccessoConsoleService {
        
        public WsUrlAccessoConsoleServiceClient() {
        }
        
        public WsUrlAccessoConsoleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsUrlAccessoConsoleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsUrlAccessoConsoleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsUrlAccessoConsoleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.WsUrlAccessoConsoleService.ConfigurazioneUrlConsole GetUrlAccessoConsole(string token, string software) {
            return base.Channel.GetUrlAccessoConsole(token, software);
        }
    }
}
