//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataClass", Namespace="http://schemas.datacontract.org/2004/07/PersonalLib2.Sql")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.BaseDataClass))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.Ateco))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Procedure.FaseAttuativaDto[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Procedure.FaseAttuativaDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Oneri.OnereDto[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Oneri.OnereDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Endoprocedimenti.FamigliaEndoprocedimentoDto[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Endoprocedimenti.FamigliaEndoprocedimentoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Endoprocedimenti.TipoEndoprocedimentoDto[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Endoprocedimenti.TipoEndoprocedimentoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Endoprocedimenti.EndoprocedimentoDto[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Endoprocedimenti.EndoprocedimentoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Endoprocedimenti.AllegatoDto[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Endoprocedimenti.AllegatoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Endoprocedimenti.TestiEstesiDto[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Endoprocedimenti.TestiEstesiDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.useForeignEnum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Utils.ClassTree<Init.SIGePro.Manager.DTO.Interventi.InterventoDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Utils.ClassTree<Init.SIGePro.Manager.DTO.Interventi.InterventoDto>[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.Ateco[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.BaseDto<int, string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.DatiDinamici.SchedaDinamicaDto[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.DatiDinamici.SchedaDinamicaDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.DatiDinamici.TipoFirmaEnum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.DatiDinamici.SchedaDinamicaInterventoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.DatiDinamici.SchedaDinamicaEndoprocedimentoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Interventi.NodoAlberoInterventiDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Interventi.InterventoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Interventi.DocumentoInterventoDto[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Interventi.DocumentoInterventoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Normative.NormativaDto[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Normative.NormativaDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.SIGePro.Manager.DTO.Common.AmbitoRicerca))]
    public partial class DataClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _orderByField;
        
        private object[] _othersJoinClauseField;
        
        private object[] _othersSelectColumnsField;
        
        private object[] _othersTablesField;
        
        private object[] _othersWhereClauseField;
        
        private string _selectColumnsField;
        
        private Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.useForeignEnum _useForeignField;
        
        private string m_dataTableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _orderBy {
            get {
                return this._orderByField;
            }
            set {
                if ((object.ReferenceEquals(this._orderByField, value) != true)) {
                    this._orderByField = value;
                    this.RaisePropertyChanged("_orderBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _othersJoinClause {
            get {
                return this._othersJoinClauseField;
            }
            set {
                if ((object.ReferenceEquals(this._othersJoinClauseField, value) != true)) {
                    this._othersJoinClauseField = value;
                    this.RaisePropertyChanged("_othersJoinClause");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _othersSelectColumns {
            get {
                return this._othersSelectColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this._othersSelectColumnsField, value) != true)) {
                    this._othersSelectColumnsField = value;
                    this.RaisePropertyChanged("_othersSelectColumns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _othersTables {
            get {
                return this._othersTablesField;
            }
            set {
                if ((object.ReferenceEquals(this._othersTablesField, value) != true)) {
                    this._othersTablesField = value;
                    this.RaisePropertyChanged("_othersTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _othersWhereClause {
            get {
                return this._othersWhereClauseField;
            }
            set {
                if ((object.ReferenceEquals(this._othersWhereClauseField, value) != true)) {
                    this._othersWhereClauseField = value;
                    this.RaisePropertyChanged("_othersWhereClause");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _selectColumns {
            get {
                return this._selectColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this._selectColumnsField, value) != true)) {
                    this._selectColumnsField = value;
                    this.RaisePropertyChanged("_selectColumns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.useForeignEnum _useForeign {
            get {
                return this._useForeignField;
            }
            set {
                if ((this._useForeignField.Equals(value) != true)) {
                    this._useForeignField = value;
                    this.RaisePropertyChanged("_useForeign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_dataTableName {
            get {
                return this.m_dataTableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.m_dataTableNameField, value) != true)) {
                    this.m_dataTableNameField = value;
                    this.RaisePropertyChanged("m_dataTableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDataClass", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.Ateco))]
    public partial class BaseDataClass : Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.DataClass {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ateco", Namespace="http://schemas.datacontract.org/2004/07/Init.SIGePro.Data")]
    [System.SerializableAttribute()]
    public partial class Ateco : Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.BaseDataClass {
        
        private bool HasChildsk__BackingFieldField;
        
        private bool HasDescriptionk__BackingFieldField;
        
        private string m_codiceField;
        
        private string m_codicebreveField;
        
        private string m_descrizioneField;
        
        private System.Nullable<int> m_fkidpadreField;
        
        private System.Nullable<int> m_idField;
        
        private string m_titoloField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<HasChilds>k__BackingField", IsRequired=true)]
        public bool HasChildsk__BackingField {
            get {
                return this.HasChildsk__BackingFieldField;
            }
            set {
                if ((this.HasChildsk__BackingFieldField.Equals(value) != true)) {
                    this.HasChildsk__BackingFieldField = value;
                    this.RaisePropertyChanged("HasChildsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<HasDescription>k__BackingField", IsRequired=true)]
        public bool HasDescriptionk__BackingField {
            get {
                return this.HasDescriptionk__BackingFieldField;
            }
            set {
                if ((this.HasDescriptionk__BackingFieldField.Equals(value) != true)) {
                    this.HasDescriptionk__BackingFieldField = value;
                    this.RaisePropertyChanged("HasDescriptionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_codice {
            get {
                return this.m_codiceField;
            }
            set {
                if ((object.ReferenceEquals(this.m_codiceField, value) != true)) {
                    this.m_codiceField = value;
                    this.RaisePropertyChanged("m_codice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_codicebreve {
            get {
                return this.m_codicebreveField;
            }
            set {
                if ((object.ReferenceEquals(this.m_codicebreveField, value) != true)) {
                    this.m_codicebreveField = value;
                    this.RaisePropertyChanged("m_codicebreve");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_descrizione {
            get {
                return this.m_descrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.m_descrizioneField, value) != true)) {
                    this.m_descrizioneField = value;
                    this.RaisePropertyChanged("m_descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> m_fkidpadre {
            get {
                return this.m_fkidpadreField;
            }
            set {
                if ((this.m_fkidpadreField.Equals(value) != true)) {
                    this.m_fkidpadreField = value;
                    this.RaisePropertyChanged("m_fkidpadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> m_id {
            get {
                return this.m_idField;
            }
            set {
                if ((this.m_idField.Equals(value) != true)) {
                    this.m_idField = value;
                    this.RaisePropertyChanged("m_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_titolo {
            get {
                return this.m_titoloField;
            }
            set {
                if ((object.ReferenceEquals(this.m_titoloField, value) != true)) {
                    this.m_titoloField = value;
                    this.RaisePropertyChanged("m_titolo");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="useForeignEnum", Namespace="http://schemas.datacontract.org/2004/07/PersonalLib2.Sql")]
    public enum useForeignEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Recoursive = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsInterventiAteco.IWsInterventiAteco")]
    public interface IWsInterventiAteco {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventiAteco/CaricaListaIdGerarchiaAteco", ReplyAction="http://tempuri.org/IWsInterventiAteco/CaricaListaIdGerarchiaAtecoResponse")]
        int[] CaricaListaIdGerarchiaAteco(string token, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventiAteco/GetAlberoProcDaIdAteco", ReplyAction="http://tempuri.org/IWsInterventiAteco/GetAlberoProcDaIdAtecoResponse")]
        Init.SIGePro.Manager.DTO.Interventi.NodoAlberoInterventiDto GetAlberoProcDaIdAteco(string token, int idAteco, Init.SIGePro.Manager.DTO.Common.AmbitoRicerca ambitoRicerca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventiAteco/GetDettagliAteco", ReplyAction="http://tempuri.org/IWsInterventiAteco/GetDettagliAtecoResponse")]
        Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.Ateco GetDettagliAteco(string token, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventiAteco/GetNodiFiglioAteco", ReplyAction="http://tempuri.org/IWsInterventiAteco/GetNodiFiglioAtecoResponse")]
        Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.Ateco[] GetNodiFiglioAteco(string token, System.Nullable<int> idPadre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventiAteco/RicercaAteco", ReplyAction="http://tempuri.org/IWsInterventiAteco/RicercaAtecoResponse")]
        Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.Ateco[] RicercaAteco(string token, string matchParziale, int matchCount, string modoRicerca, string tipoRicerca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsInterventiAteco/VerificaEsistenzaNodiCollegatiAIdAteco", ReplyAction="http://tempuri.org/IWsInterventiAteco/VerificaEsistenzaNodiCollegatiAIdAtecoRespo" +
            "nse")]
        bool VerificaEsistenzaNodiCollegatiAIdAteco(string token, string software, int idAteco, Init.SIGePro.Manager.DTO.Common.AmbitoRicerca ambitoRicerca);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsInterventiAtecoChannel : Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.IWsInterventiAteco, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsInterventiAtecoClient : System.ServiceModel.ClientBase<Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.IWsInterventiAteco>, Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.IWsInterventiAteco {
        
        public WsInterventiAtecoClient() {
        }
        
        public WsInterventiAtecoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsInterventiAtecoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsInterventiAtecoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsInterventiAtecoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] CaricaListaIdGerarchiaAteco(string token, int id) {
            return base.Channel.CaricaListaIdGerarchiaAteco(token, id);
        }
        
        public Init.SIGePro.Manager.DTO.Interventi.NodoAlberoInterventiDto GetAlberoProcDaIdAteco(string token, int idAteco, Init.SIGePro.Manager.DTO.Common.AmbitoRicerca ambitoRicerca) {
            return base.Channel.GetAlberoProcDaIdAteco(token, idAteco, ambitoRicerca);
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.Ateco GetDettagliAteco(string token, int id) {
            return base.Channel.GetDettagliAteco(token, id);
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.Ateco[] GetNodiFiglioAteco(string token, System.Nullable<int> idPadre) {
            return base.Channel.GetNodiFiglioAteco(token, idPadre);
        }
        
        public Init.Sigepro.FrontEnd.AppLogic.WsInterventiAteco.Ateco[] RicercaAteco(string token, string matchParziale, int matchCount, string modoRicerca, string tipoRicerca) {
            return base.Channel.RicercaAteco(token, matchParziale, matchCount, modoRicerca, tipoRicerca);
        }
        
        public bool VerificaEsistenzaNodiCollegatiAIdAteco(string token, string software, int idAteco, Init.SIGePro.Manager.DTO.Common.AmbitoRicerca ambitoRicerca) {
            return base.Channel.VerificaEsistenzaNodiCollegatiAIdAteco(token, software, idAteco, ambitoRicerca);
        }
    }
}
