//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Init.Sigepro.FrontEnd.AppLogic.CommissioniAccessoPINWs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommissioniAccessoPINWs.IWsCommissioniAccessoPIN")]
    public interface IWsCommissioniAccessoPIN {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCommissioniAccessoPIN/VerificaValiditaPIN", ReplyAction="http://tempuri.org/IWsCommissioniAccessoPIN/VerificaValiditaPINResponse")]
        bool VerificaValiditaPIN(string token, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsCommissioniAccessoPIN/AssociaUtenteACommissioneByPIN", ReplyAction="http://tempuri.org/IWsCommissioniAccessoPIN/AssociaUtenteACommissioneByPINRespons" +
            "e")]
        int AssociaUtenteACommissioneByPIN(string token, int codiceAnagrafe, string pin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsCommissioniAccessoPINChannel : Init.Sigepro.FrontEnd.AppLogic.CommissioniAccessoPINWs.IWsCommissioniAccessoPIN, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsCommissioniAccessoPINClient : System.ServiceModel.ClientBase<Init.Sigepro.FrontEnd.AppLogic.CommissioniAccessoPINWs.IWsCommissioniAccessoPIN>, Init.Sigepro.FrontEnd.AppLogic.CommissioniAccessoPINWs.IWsCommissioniAccessoPIN {
        
        public WsCommissioniAccessoPINClient() {
        }
        
        public WsCommissioniAccessoPINClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsCommissioniAccessoPINClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsCommissioniAccessoPINClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsCommissioniAccessoPINClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool VerificaValiditaPIN(string token, string pin) {
            return base.Channel.VerificaValiditaPIN(token, pin);
        }
        
        public int AssociaUtenteACommissioneByPIN(string token, int codiceAnagrafe, string pin) {
            return base.Channel.AssociaUtenteACommissioneByPIN(token, codiceAnagrafe, pin);
        }
    }
}
